{{- if and (not .Values.llm.existingSecret) .Values.llm.apiKey }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-llm
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
type: Opaque
stringData:
  api-key: {{ .Values.llm.apiKey | quote }}
{{- end }}
---
{{- if and .Values.slack.enabled (not .Values.slack.existingSecret) .Values.slack.webhook }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-slack
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
type: Opaque
stringData:
  webhook-url: {{ .Values.slack.webhook | quote }}
{{- end }}
