# Controller configuration
controller:
  image:
    repository: ghcr.io/adiii717/kube-ai-sre-agent-controller
    tag: latest
    pullPolicy: IfNotPresent

  resources:
    requests:
      cpu: 10m
      memory: 20Mi
    limits:
      cpu: 100m
      memory: 64Mi

  replicas: 1

# Analyzer Job configuration
analyzer:
  image:
    repository: ghcr.io/adiii717/kube-ai-sre-agent-analyzer
    tag: latest
    pullPolicy: IfNotPresent

  resources:
    requests:
      cpu: 500m
      memory: 512Mi
    limits:
      cpu: 1000m
      memory: 1Gi

  # Job TTL after completion (seconds) - cleanup old jobs
  ttlSecondsAfterFinished: 300

  # Maximum number of retries for failed jobs
  backoffLimit: 2

  # Job timeout - kill job if it runs longer than this (seconds)
  activeDeadlineSeconds: 600  # 10 minutes max

# Alert deduplication and noise reduction
deduplication:
  # Initial cooldown period - don't analyze same incident within this time
  cooldownMinutes: 5

  # Smart escalation - silence noisy incidents
  # Example: If a pod crashes 10 times in 5 minutes, it's permanently broken
  # → silence it for 1 hour to prevent alert noise
  escalation:
    enabled: true
    # If incident occurs this many times within cooldown period
    threshold: 10
    # Then silence it for this long (minutes)
    silenceDurationMinutes: 60  # 1 hour

    # Configuration examples:
    # Aggressive (quick to silence):
    #   cooldownMinutes: 2
    #   threshold: 3
    #   silenceDurationMinutes: 30
    #   → If crashes 3 times in 2 minutes, silence for 30 minutes
    #
    # Conservative (tolerant of transient issues):
    #   cooldownMinutes: 10
    #   threshold: 20
    #   silenceDurationMinutes: 120
    #   → If crashes 20 times in 10 minutes, silence for 2 hours

# Event filters - which events to monitor
events:
  crashLoopBackOff: true
  imagePullBackOff: true
  healthCheckFailure: true
  oomKilled: true

# LLM configuration
llm:
  # Provider: gemini, claude, or openai
  provider: gemini

  # API key (can also be set via secret)
  apiKey: ""

  # Secret name if using existing secret
  existingSecret: ""
  existingSecretKey: "api-key"

  # Model configuration
  model:
    gemini: "gemini-pro"
    claude: "claude-3-5-sonnet-20241022"
    openai: "gpt-4"

  # Max tokens for analysis
  maxTokens: 1000

# Slack notification configuration
slack:
  enabled: true
  webhook: ""

  # Existing secret for webhook
  existingSecret: ""
  existingSecretKey: "webhook-url"

  # Channel override (if webhook supports it)
  channel: ""

# Namespace to monitor (empty = all namespaces)
# Note: Requires cluster-wide RBAC if monitoring all namespaces
watchNamespace: ""

# Service account
serviceAccount:
  create: true
  name: kube-ai-sre-agent
  annotations: {}

# RBAC
rbac:
  create: true

# Pod annotations
podAnnotations: {}

# Node selector
nodeSelector: {}

# Tolerations
tolerations: []

# Affinity
affinity: {}
